# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: 
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          17,    # Current Java LTS & minimum supported by Minecraft
        ]
        # and run on both Linux and Windows
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: build fabric
        run: |
          cd fabric
          chmod +x ./gradlew
          ./gradlew build

      - name: build forge
        run: |
          cd forge
          chmod +x ./gradlew
          ./gradlew build

      - name: capture build artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Artifacts
          path: |
            fabric/build/libs/
            forge/build/libs/