# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: setup jdk 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: build 
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
            common/build/libs/
            fabric/build/libs/
            neoforge/build/libs/

  release:
    needs: build
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
      
      - name: Remove dev-shadow jars
        run: |
          rm -f build/libs/fabric/build/libs/*dev-shadow*.jar
          rm -f build/libs/fabric/build/libs/*dev-shadow*.jar
          rm -f build/libs/neoforge/build/libs/*dev-shadow*.jar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Version ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            build/libs/fabric/build/libs/MCLLM-fabric-${{github.ref_name}}.jar
            build/libs/neoforge/build/libs/MCLLM-neoforge-${{github.ref_name}}.jar
            build/libs/common/build/libs/MCLLM-common-${{github.ref_name}}-sources.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}